### ISSUE TITLE
WP Plugin: Unlock Content button not working properly

### ISSUE THREAD

**Issue by AlexandrUrita** [MitocGroup/adtechmedia-wordpress-plugin#104]
Steps to reproduce:
1. Install and activate WP plugin
2. Navigate to configuration of plugin
3. Locate Content Configuration section
4. Make changes (example: Change paragraphs -> words)
5. Click on Save button
6. Click on Unlock Content button

Expected Result: On preview page changes should be applied

Actual Result: Unlock Content duplicate behavior of Save button
![screen shot 2017-06-20 at 13 29 14](https://user-images.githubusercontent.com/27765884/27328981-9d51ff52-55bc-11e7-9778-14869b6019e1.png)

**Comment by AlexanderC** [comment]
This is not a preview, this is a mock that is not supposed to be updated
