### ISSUE TITLE
WP Plugin: Mismatch data between connected user and selected payment card   

### ISSUE THREAD

**Issue by AlexandrUrita** [MitocGroup/adtechmedia-wordpress-plugin#105]
Steps to reproduce:
0. Navigate to Post with activated WP plugin  
1. Expand widget
2. Click on ```Connect here``` link
3. Proceed with valid email and enter to the system
4. Click on ```Follow this link```
5. Click on ```Pay with Card``` button

Expected Result: Fields should be populated with previously setup payment card

Actual Result: Fields are populated with valid data (except card number). On preview card module data has default values.
Please refer to the screenshot below:

![screen shot 2017-06-21 at 10 59 30](https://user-images.githubusercontent.com/27765884/27373987-e4981db8-5672-11e7-8310-f58e415c5285.png)

**Comment by AlexanderC** [comment]
Please move this issue to ATM repository
