### ISSUE TITLE
Wordpress: Templates Management Styles for large resolution

### ISSUE THREAD

**Issue by AlexandrUrita** [MitocGroup/adtechmedia-wordpress-plugin#110]
Steps to reproduce:
1. Install and Activate plugin on Wordpress
2. Navigate to Adtechmedia plugin
3. Expand window to full screen (resolution should be 1920*1080 FullHD)
4. Scroll down the page till Templates Management section

Expected Result: Section should fill all area. No borders should be displayed

Actual Result: On FullHD dimention there are borders around templates

![screen shot 2017-06-27 at 11 06 03 2](https://user-images.githubusercontent.com/27765884/27577527-b45eb4de-5b29-11e7-9b49-afd7db644c88.png)

**Comment by avozicov** [comment]
**Test Passed**
![screen shot 2017-07-04 at 14 10 12 2](https://user-images.githubusercontent.com/12330493/27827992-971c75d4-60c2-11e7-8667-1c087306f9f4.png)
