### ISSUE TITLE
Wordpress: Add different errors messages for better user experience

### ISSUE THREAD

**Issue by AlexandrUrita** [MitocGroup/adtechmedia-wordpress-plugin#112]
One possible example for error message:

Steps to reproduce:
1. Install plugin and send link to valid email
2. Wait 24 hours
3. Return on email that has link with activation
4. Click on link

@ivignan @eistrati - Please correct expected error message when Token is expired

Expected Result: User should be redirected to Wordpress on Adtechmedia plugin with following error message: Your Token was expired, please re-send activation link.

Actual Result:  User is redirected to Wordpress on Adtechmedia plugin with error message: An error occur. API key has not .... (please refer to the screenshot below:)
![adtechmedia wordpress 2017-06-27 08-52-05 1](https://user-images.githubusercontent.com/27765884/27589064-bef84f12-5b52-11e7-83a5-4ea24811ac2f.png)

**Comment by eistrati** [comment]
Let's change to the following message:

_We detected a delayed response from AdTechMedia platform. Please reload the page to try again. If this problem persists, contact us at support@adtechmedia.io_

**Comment by AlexandrUrita** [comment]
Error message was changed:
![screen shot 2017-08-28 at 11 13 08](https://user-images.githubusercontent.com/27765884/29764993-0c0354fe-8be2-11e7-9205-8871615a7c2b.png)
