### ISSUE TITLE
Data from ATM is not being catched into wordpress

### ISSUE THREAD

**Issue by grigoreme** [MitocGroup/adtechmedia-wordpress-plugin#113]
More details [here](https://github.com/MitocGroup/atm/issues/921)

**Comment by AlexanderC** [comment]
See https://github.com/MitocGroup/atm/issues/921#issuecomment-311998151

**Comment by grigoreme** [comment]
After some researches i find out that wordpress is getting wrong property data:
Wordpress retrieve: 
```
{
        "AccountId":"3e0564f0-67b2-11e7-976b-c591a1fb5a46",
        "SupportEmail":"grigore997@gmail.com",
        "Country":"United States",
        "ThemeId":"0779b9e0-67bc-11e7-bd7b-3b8b320a6382",
        "updatedAt":"2017-07-13T11:11:34.616Z",
        "Config":{...},
        "Website":"http://localhost:8888",
        "createdAt":"2017-07-13T11:11:27.942Z",
        "BuildPath":"https://www-test.adtechmedia.io/atm-admin/04275a90-67bc-11e7-ae71-edf61fb50952/atm.min.js",
        "Id":"04275a90-67bc-11e7-ae71-edf61fb50952",
        "Name":"localhost:8888"
    }
```

Admin update:
```
{
        "AccountId":"3e0564f0-67b2-11e7-976b-c591a1fb5a46",
        "SupportEmail":"grigore997@gmail.com",
        "Country":"United States",
        "ThemeId":"0779b9e0-67bc-11e7-bd7b-3b8b320a6382",
        "updatedAt":"2017-07-13T11:11:34.616Z",
        "Config":{...},
        "Website":"http://localhost:8888",
        "createdAt":"2017-07-13T11:11:27.942Z",
        "BuildPath":"https://www-test.adtechmedia.io/atm-admin/04275a90-67bc-11e7-ae71-edf61fb50952/atm.min.js",
        "Id":"04275a90-67bc-11e7-ae71-edf61fb50952",
        "Name":"localhost:8888"
    }
```

Data is being gathered right from api to wordpress and shown on the screen fake/cached data.

**Comment by AlexandrUrita** [comment]
Build was received for QA on 14.07.2017 (new environment was created www-test)

**Comment by AlexandrUrita** [comment]
There is one issue that may affect current one. Waiting when fix will be ready for - https://github.com/AdTechMedia/wordpress-plugin/issues/146

**Comment by AlexandrUrita** [comment]
FYI: Test actions cannot be performed because of the new approach of environments. Manage and website are separate in test env. Developers are working now to resolve related issues
Blocked by: https://github.com/MitocGroup/atm/issues/1107

**Comment by AlexandrUrita** [comment]
Issue resolved. Changes are working in both directions. WP Plugin <-> Manage website
![screen shot 2017-07-20 at 16 40 31](https://user-images.githubusercontent.com/27765884/28420283-4fa6fea4-6d6a-11e7-97cc-cce9cbf3a5de.png)
![screen shot 2017-07-20 at 16 40 36](https://user-images.githubusercontent.com/27765884/28420284-4fad4c1e-6d6a-11e7-8971-aa0c44a4eb28.png)
