### ISSUE TITLE
Improve and speed up plugin confirmation process

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/adtechmedia-wordpress-plugin#115]
Currently, when clicking on link from confirmation email with atm-token in URL, the WP admin page doesn't show up until the process is finished. Please improve and speed up confirmation process by showing the admin page in the first place and adding a spinner to let user know that the work is in progress, as well as review the code to speed up confirmation process.

**Comment by AlexandrUrita** [comment]
Spinner was added for second activation of plugin when client activates for second time plugin on existing user
![screen shot 2017-07-07 at 11 02 46](https://user-images.githubusercontent.com/27765884/27950996-05cf9c7c-630c-11e7-8f36-eea0131befaf.png)
