### ISSUE TITLE
Add explicit link in confirmation email

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/adtechmedia-wordpress-plugin#116]
Add explicit link in confirmation email, for situations like Radu's where email client is stripping HTML tags from email body.

**Comment by AlexandrUrita** [comment]
This item did`t get in the new dev build that was received for QA on 07.07.2017 (d8gi9uvvjasve.cloudfront.net)

**Comment by AlexandrUrita** [comment]
New build for QA was received on 07.07.2017 (d3qpdk1g0ojf0w.cloudfront.net)

**Comment by AlexandrUrita** [comment]
New line was added to email. Please see attached screenshots:
<img width="856" alt="screen shot 2017-07-07 at 16 26 47" src="https://user-images.githubusercontent.com/27765884/27959998-49e1f862-6332-11e7-9985-4106ae394809.png">
<img width="851" alt="screen shot 2017-07-07 at 16 34 43" src="https://user-images.githubusercontent.com/27765884/27959999-49e96886-6332-11e7-865d-f6e07574b23f.png">
