### ISSUE TITLE
Fix broken template management

### ISSUE THREAD

**Issue by AlexanderC** [MitocGroup/adtechmedia-wordpress-plugin#117]
See the screenshot attached:

![screen shot 2017-06-29 at 22 18 14](https://user-images.githubusercontent.com/1415757/27723190-847dff7a-5d74-11e7-8d1c-f2e86290aac4.png)

**Comment by AlexandrUrita** [comment]
New dev build received for QA on 07.07.2017

**Comment by AlexandrUrita** [comment]
Issue resolved:
![screen shot 2017-07-07 at 10 39 34](https://user-images.githubusercontent.com/27765884/27947956-a328e714-6300-11e7-98fe-b678f5de4d00.png)
