### ISSUE TITLE
Widget styles become applied only after performing "save config" for atm plugin

### ISSUE THREAD

**Issue by veronicamacovei** [MitocGroup/adtechmedia-wordpress-plugin#121]
Prerequisites: 
WordPress Version - 4.5.9
ATM plugin is activated for the first time, this is a new user

_Steps to reproduce:_
- Install and Activate "AdTechMedia" plugin
- Navigate to "content" page

_BUG:_
- ATM Widget view  does not match default configuration styles

_Note:_
- Required styles become applied only after performing "save config" for atm plugin

_Please refer to attachment for more details:_
**Default Styles** 
<img width="1134" alt="screen shot 2017-07-05 at 3 54 14 pm" src="https://user-images.githubusercontent.com/17923747/27865316-cf919d12-619a-11e7-9c1d-fe99d53a905d.png">

**Without performing Save Config** 
<img width="668" alt="screen shot 2017-07-05 at 4 01 34 pm" src="https://user-images.githubusercontent.com/17923747/27865468-5376c396-619b-11e7-906a-df1615254321.png">

**Expected Result**
<img width="698" alt="screen shot 2017-07-05 at 5 34 06 pm" src="https://user-images.githubusercontent.com/17923747/27869323-3ee92f88-61a8-11e7-9673-3a75a55c5064.png">

**Comment by AlexandrUrita** [comment]
Issue is fixed:
![screen shot 2017-07-10 at 19 29 15](https://user-images.githubusercontent.com/27765884/28028715-1f1cd770-65a6-11e7-9e9c-ea5e25214939.png)
![screen shot 2017-07-10 at 19 27 50](https://user-images.githubusercontent.com/27765884/28028722-24b80164-65a6-11e7-9957-337fd7c906e4.png)
