### ISSUE TITLE
Default styling and positioning per WP theme

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/adtechmedia-wordpress-plugin#13]
Add default styling and positioning for known wordpress themes.

**Comment by icovali** [comment]
If **default theme** is used:

Positioning:
- sticky
- _width_: 600px;
- _offset top_: 20px;
- _offset from center_: -60px;
- _scrolling offset top_: 100px;

Styling:
- _background-color_: #fff;
- _border_: 1px solid #d3d3d3;
- _font-family_: Merriweather;
- _box-shadow_: 0 1px 2px 0 rgba(0, 0, 0, 0.1);
- _footer-background_: #fafafa;
- _footer-border-top_: 1px solid #e3e3e3;

**Comment by eistrati** [comment]
Make default styling and positioning per WP theme

**Comment by ghost** [comment]
See attached: please make sure the font-family is `Merriweather`

<img width="571" alt="screen shot 2017-01-23 at 10 52 31 am" src="https://cloud.githubusercontent.com/assets/10956412/22197297/142f5480-e15a-11e6-8d23-1502db246e08.png">

**Comment by eistrati** [comment]
@dsasov Ignore `Merriweather` font for the time being

**Comment by eistrati** [comment]
Verified.
