### ISSUE TITLE
Currencies are not properly displayed into WP admin 

### ISSUE THREAD

**Issue by mgoria** [MitocGroup/adtechmedia-wordpress-plugin#135]
When selecting a specific country all currencies are displayed into currencies dropdown, while only country supported currencies should be displayed.

![screen shot 2017-07-13 at 3 57 15 pm](https://user-images.githubusercontent.com/2959952/28167362-12679c96-67e4-11e7-84b9-4e700321354e.png)

**Comment by AlexandrUrita** [comment]
issue is blocked by: https://github.com/AdTechMedia/wordpress-plugin/issues/146

**Comment by AlexandrUrita** [comment]
FYI: Test actions cannot be performed because of the new approach of environments. Manage and website are separate in test env. Developers are working now to resolve related issues
Blocked by: https://github.com/MitocGroup/atm/issues/1107

**Comment by AlexandrUrita** [comment]
Issue blocked by https://github.com/AdTechMedia/wordpress-plugin/issues/155

**Comment by AlexandrUrita** [comment]
Issue resolved. Please see attached screenshots:
![screen shot 2017-07-21 at 11 26 49](https://user-images.githubusercontent.com/27765884/28455390-a1b17e5c-6e07-11e7-87e7-4f40ade8c9ba.png)
![screen shot 2017-07-21 at 11 26 31](https://user-images.githubusercontent.com/27765884/28455392-a1b70ce6-6e07-11e7-96d1-08ac46730caf.png)
![screen shot 2017-07-21 at 11 26 41](https://user-images.githubusercontent.com/27765884/28455391-a1b2cb7c-6e07-11e7-9d9a-7a70f8d2441f.png)
![screen shot 2017-07-21 at 11 26 59](https://user-images.githubusercontent.com/27765884/28455393-a1b80e3e-6e07-11e7-8ef8-741c4eebbd3a.png)
