### ISSUE TITLE
Split calls to ATM api when activating WP plugin

### ISSUE THREAD

**Issue by mgoria** [MitocGroup/adtechmedia-wordpress-plugin#136]
When activating the plugin two atm api calls are executed (`/client/register and /property/create`) which makes activation very slow.
Please move `/property/create` call to be executed when navigating to adtechmedia plugin itself.

**Comment by ciolak** [comment]
Во время нажатия активация выполняются 4 функции:

$this->check_api_key_exists();       //     /deep-account/client/register
$this->check_prop();                    //      /atm-admin/property/create
$this->update_prop();                  //     /atm-admin/property/update-config
$this->update_appearance();      //     /atm-admin/property/update-config

Время активации примерно 30-40 секунд.

Проанализировав, я понял что можно удалить $this->check_prop(); ,потому что, эта функция вызывается при заходе на страницу плагина.

Так же можно выключить $this->update_prop(); , т.к. она вызывается в конце $this->check_prop();

Остаются:
$this->check_api_key_exists();
$this->update_appearance();

Время активации примерно 20-30 секунд.

$this->update_appearance(); из них занимает где то 70% времени. Эта функция добавлялась недавно, надо уточнить у  AlexanderC  возможно ли его вывести как то из активации.

Теоретически можно снизить активацию до 5 - 10 секунд, но при первом заходе на страницу плагина, запуститься функция впервые $this->check_prop(); и будет задержка.

**Comment by ciolak** [comment]
Please test on WP 4.8 and 4.5

**Comment by AlexandrUrita** [comment]
Build was received for QA on 14.07.2017 (new environment was created www-test)

**Comment by AlexandrUrita** [comment]
Issue was checked and 30 seconds activation passed. Please see attached gif files
![activation on 4 5 9](https://user-images.githubusercontent.com/27765884/28311355-18e75cbe-6bb8-11e7-849b-3f768ddc0437.gif)
![activation on 4 8](https://user-images.githubusercontent.com/27765884/28311356-18ec4bd4-6bb8-11e7-85ff-b40f794e872b.gif)

However after researches we discovered that activation time can be reduced more. By moving $this->update_appearance(); under some background processes (ajax)

**Comment by AlexandrUrita** [comment]
Activation of plugin takes 6 seconds for the first time. And for the same email for second time less than 5 seconds
