### ISSUE TITLE
WP plugin on test environment - PayPal and Amazon are not working

### ISSUE THREAD

**Issue by AlexandrUrita** [MitocGroup/adtechmedia-wordpress-plugin#138]
Steps to reproduce:
0. Install WP
1. Install Adtechmedia plugin
2. Make sure that plugin is pointing on test environment 
(in main.js file -> find a line with -> islocalhost ('**test**', 'prod') change dev -> test
in config file -> replace dev -> test)
3. On post with applied plugin simulate behavior when payment is available
4. Try to pay with amazon or paypal

Expected Result: user should be able to enter credentials

Actual Result: user cannot enter credentials

Please see attached screenshots:
![screen shot 2017-07-13 at 18 52 44](https://user-images.githubusercontent.com/27765884/28177007-085a93f2-6802-11e7-9726-5a368c01c418.png)
![screen shot 2017-07-13 at 18 53 08](https://user-images.githubusercontent.com/27765884/28177008-085e305c-6802-11e7-9272-ef81aa61693c.png)

**Comment by AlexanderC** [comment]
It's not supposed to work on localhost, please test in in dev/test deploys
