### ISSUE TITLE
Research metadata that could be used by BRs

### ISSUE THREAD

**Issue by AlexanderC** [MitocGroup/adtechmedia-wordpress-plugin#145]

**Comment by AlexanderC** [comment]
The following metadata could be extracted:
- `category` https://codex.wordpress.org/Template_Tags/the_category
- `time` https://codex.wordpress.org/Template_Tags/the_time
- `url` https://developer.wordpress.org/reference/functions/get_permalink/
- `id` https://developer.wordpress.org/reference/functions/get_the_id/
- `tags` https://codex.wordpress.org/Function_Reference/get_the_tags

**Comment by eistrati** [comment]
@AlexanderC perfect. let's use everything except `id` (I don't see any use cases for that).

**Comment by AlexandrUrita** [comment]
FYI: Test actions cannot be performed because of the new approach of environments. Manage and website are separate in test env. Developers are working now to resolve related issues
Blocked by: https://github.com/MitocGroup/atm/issues/1107

**Comment by AlexandrUrita** [comment]
Only documentation. Nothing for QA for now
