### ISSUE TITLE
Add A/B testing library for BRs

### ISSUE THREAD

**Issue by AlexanderC** [MitocGroup/adtechmedia-wordpress-plugin#149]

**Comment by AlexandrUrita** [comment]
New functionality is working. Please refer to the screenshots:
![screen shot 2017-07-20 at 15 47 01](https://user-images.githubusercontent.com/27765884/28418003-d7160af4-6d62-11e7-9fbc-6628958fe872.png)
![screen shot 2017-07-20 at 15 47 07](https://user-images.githubusercontent.com/27765884/28418004-d71ad228-6d62-11e7-8271-83d0060add3b.png)
![screen shot 2017-07-20 at 15 47 20](https://user-images.githubusercontent.com/27765884/28418008-ddc50526-6d62-11e7-92f0-a3835457ca1d.png)
![screen shot 2017-07-20 at 15 47 36](https://user-images.githubusercontent.com/27765884/28418009-dde4f106-6d62-11e7-8043-08b9cd5deda1.png)
