### ISSUE TITLE
Widget plugin is not working

### ISSUE THREAD

**Issue by AlexandrUrita** [MitocGroup/adtechmedia-wordpress-plugin#152]
Steps to reproduce:
1. Install WP
2. Install Plugin and activate it
3. Navigate to plugin config
4. Navigate to post with plugin 

Actual result: Plugin is not applied
![screen shot 2017-07-19 at 16 23 10](https://user-images.githubusercontent.com/27765884/28368887-990c17e0-6c9e-11e7-80bb-4e2bfd8e6616.png)

Expected result: Plugin should be applied on post

**Comment by AlexanderC** [comment]
You have to set to `100` A/B settings from general section

**Comment by AlexandrUrita** [comment]
With parameter 100 page cannot be load:
![screen shot 2017-07-19 at 16 32 10](https://user-images.githubusercontent.com/27765884/28369322-e853f4c0-6c9f-11e7-9356-d4b4b56cbc28.png)

**Comment by AlexandrUrita** [comment]
Widget is working.
![screen shot 2017-07-20 at 15 47 36](https://user-images.githubusercontent.com/27765884/28418048-063ba3c0-6d63-11e7-988d-d18334fe513c.png)
