### ISSUE TITLE
WP plugin do not update property from Admin site

### ISSUE THREAD

**Issue by AlexandrUrita** [MitocGroup/adtechmedia-wordpress-plugin#157]
Steps to reproduce:
0. WP should be installed and plugin activated and registered in Admin
1. Open any post with applied plugin
2. Change configuration of widget from Admin
3. Observe that changes are applied on widget

Expected result: Changes that are made from Admin site should update property on WP plugin and on Widget

Actual result: Need to refresh the WP plugin (filed will be updated with changes), Need to click on save button (changes will be applied)

**Comment by avozicov** [comment]
**Test Passed**
<img width="629" alt="screen shot 2017-07-31 at 11 27 45" src="https://user-images.githubusercontent.com/12330493/28769250-63660026-75e3-11e7-9066-e3cd021a484d.png">
<img width="475" alt="screen shot 2017-07-31 at 11 27 50" src="https://user-images.githubusercontent.com/12330493/28769251-6368a984-75e3-11e7-9a80-437eaa371fd8.png">
<img width="513" alt="screen shot 2017-07-31 at 11 27 56" src="https://user-images.githubusercontent.com/12330493/28769252-6368fefc-75e3-11e7-902a-a68a8f421e08.png">
<img width="671" alt="screen shot 2017-07-31 at 11 28 01" src="https://user-images.githubusercontent.com/12330493/28769253-636d5a06-75e3-11e7-9570-df0edec0735f.png">
