### ISSUE TITLE
Redundant error message on confirming identity for already registered users 

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/adtechmedia-wordpress-plugin#163]
_Pre-requisites:_
- user should be already registered in system 

_Steps to reproduce:_
1. Perform plugin activation 
2. Confirm your identity 

_BUG:_
- Once the user perform identity confirmation there is an redundant error message displayed on plugin admin page

_Please refer to attachment for more details:_
<img width="1280" alt="screen shot 2017-07-26 at 11 20 20" src="https://user-images.githubusercontent.com/12330493/28611585-ee8efbfa-71f4-11e7-928e-b0189430e02e.png">

**Comment by AlexandrUrita** [comment]
Issue resolved:
![screen shot 2017-08-01 at 17 05 09](https://user-images.githubusercontent.com/27765884/28829468-81328ea4-76dc-11e7-8027-695b9528bf36.png)
