### ISSUE TITLE
Currency is not changed on Manage Site within for country

### ISSUE THREAD

**Issue by AlexandrUrita** [MitocGroup/adtechmedia-wordpress-plugin#164]
Steps to reproduce:
1. Install WP
2. Install and Activate Plugin
3. Register plugin on Manage Site
4. Return back to WP plugin Admin part and make following changes:
- Country -> United Kingdom
- Currency -> EUR
5. Save changes by clicking on the top Save button
6. Navigate to Manage Site
7. Refresh page on Configurations

Expected result: Currency should be EUR

Actual result: Currency remained as GBP

![screen shot 2017-07-26 at 11 41 30](https://user-images.githubusercontent.com/27765884/28612597-77ecdacc-71f8-11e7-8f67-3da4168821fd.png)

![screen shot 2017-07-26 at 11 41 37](https://user-images.githubusercontent.com/27765884/28612583-6d8f8d54-71f8-11e7-9d87-df06a21b1727.png)

**Comment by avozicov** [comment]
**Test Passed**
<img width="629" alt="screen shot 2017-07-31 at 11 27 45" src="https://user-images.githubusercontent.com/12330493/28769282-7dc81a76-75e3-11e7-817a-47d3cafd332f.png">
<img width="513" alt="screen shot 2017-07-31 at 11 27 56" src="https://user-images.githubusercontent.com/12330493/28769283-7dcbb05a-75e3-11e7-9599-7871b4dd23fe.png">
