### ISSUE TITLE
Move A/B input to "CONTENT CONFIGURATION" section

### ISSUE THREAD

**Issue by AlexanderC** [MitocGroup/adtechmedia-wordpress-plugin#166]
Move A/B input to "CONTENT CONFIGURATION" section in the same row as " Content unlocking algorithm" (50/50 of width both)

**Comment by AlexandrUrita** [comment]
A/B was moved to Content configuration section
![screen shot 2017-08-17 at 16 39 29](https://user-images.githubusercontent.com/27765884/29415170-cc20ccba-836a-11e7-83e4-df2fc8593acd.png)
