### ISSUE TITLE
We need to block atm.js for http sites 

### ISSUE THREAD

**Issue by ivignan** [MitocGroup/adtechmedia-wordpress-plugin#169]
Related tasks - https://github.com/AdTechMedia/wordpress-plugin/issues/45

Please work with @AlexanderC for more details

**Comment by ciolak** [comment]
The error could not be reproduced, even in http. Please put a screen and conditions when he appears

**Comment by AlexandrUrita** [comment]
Issue cannot be reproduced:
![screen shot 2017-08-01 at 15 35 03](https://user-images.githubusercontent.com/27765884/28825501-147cb972-76cf-11e7-8223-69d3caa5245a.png)
