### ISSUE TITLE
Plugin not displayed on AMP pages

### ISSUE THREAD

**Issue by AlexanderC** [MitocGroup/adtechmedia-wordpress-plugin#180]
See https://coolosophy.ro/frizuri-barbati/amp/

**Comment by AlexandrUrita** [comment]
@eistrati This issue requires a lot of changes (backend and frontend) and it will be time consuming. After fix will be implemented QA will not be manage to check all possible scenarios for AMP pages.
But we have a perfect solution for this situation. For AMP pages we can show some sort of preview page with button (for example: For full content click here) which will navigate to non-AMP page with possibilities of buying content. Just one redirection from our demo page to real product possibilities.

**Comment by AlexandrUrita** [comment]
After conversation with @eistrati this issue can be closed. We will open an enhancement that should resolve current issue with AMP pages
