### ISSUE TITLE
Diacritics are broken when saving content

### ISSUE THREAD

**Issue by AlexanderC** [MitocGroup/adtechmedia-wordpress-plugin#182]

**Comment by AlexanderC** [comment]
It seems to be an database encoding issues, it works on localhost with UTF-8 encoding

<img width="1037" alt="screen shot 2017-08-04 at 12 29 53" src="https://user-images.githubusercontent.com/1415757/28963121-a619f1fe-7910-11e7-9e81-163b1e34cf17.png">

**Comment by eistrati** [comment]
@AlexanderC @AlexandrUrita Did you guy try to test it in multiple browsers? When I tested yesterday, it worked for me in Firefox, but didn't work in Chrome (or the other way around).

**Comment by avozicov** [comment]
**Test Passed**
Browsers:
- Safari Version 10.1.2 | Chrome Version 59.0.3071.115 | Firefox 54.0.1

<img width="1280" alt="screen shot 2017-08-08 at 16 51 00" src="https://user-images.githubusercontent.com/12330493/29075066-ffe2f8b0-7c59-11e7-9f2b-cce1b84412b8.png">
<img width="1280" alt="screen shot 2017-08-08 at 16 51 48" src="https://user-images.githubusercontent.com/12330493/29075067-000268d0-7c5a-11e7-948e-99a33b4e072b.png">
<img width="1280" alt="screen shot 2017-08-08 at 16 52 05" src="https://user-images.githubusercontent.com/12330493/29075068-000598fc-7c5a-11e7-8d07-7ab43cbe608a.png">
