### ISSUE TITLE
Templates Management component is not displayed in ATM Plugin Settings

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/adtechmedia-wordpress-plugin#183]
_Steps to reproduce:_

- Navigate to ATM Plugin Settings page

_Bug:_
- Templates Management component is not displayed
- Console Error 
`manager.js:317 Uncaught Error: Unable to load ATM Templates Library from window.atmTpl`

_Environment:_

- Test 
- Safari Version 10.1.2 | Chrome Version 59.0.3071.115 | Firefox 54.0.1 

_Please refer to attachment for more details:_
<img width="1280" alt="screen shot 2017-08-04 at 23 43 53" src="https://user-images.githubusercontent.com/12330493/28986387-717881a4-796f-11e7-8469-a7eded099958.png">

**Comment by AlexanderC** [comment]
Seems like the script haven't been deployed at all. Please check deploy with @ddimitrioglo.

**Comment by avozicov** [comment]
Bug is reproducing in new test build
![screen shot 2017-08-07 at 14 13 21](https://user-images.githubusercontent.com/12330493/29024482-ea1dba54-7b7a-11e7-96ca-b85d566efb4c.png)

**Comment by avozicov** [comment]
Issue is not reproduce anymore.
Note there is a different issue described here 
https://github.com/AdTechMedia/wordpress-plugin/issues/186
