### ISSUE TITLE
Long time applying for the first time to any posts

### ISSUE THREAD

**Issue by AlexandrUrita** [MitocGroup/adtechmedia-wordpress-plugin#193]
1. Install WP
2. Activate plugin with property
3. Open post with activated plugin

Expected result: Post should be running fast like w/o activated plugin (almost)

Actual result: First applying to the post takes too much time

**Comment by AlexandrUrita** [comment]
@eistrati Some performance optimisations were made. We took a look of how post is opening with our plugin and now it is faster than it was.
Could you please double check and tell if you are OK.

**Comment by AlexanderC** [comment]
Related task: https://github.com/AdTechMedia/wordpress-plugin/issues/199

**Comment by AlexandrUrita** [comment]
Will be closed after: #199

**Comment by AlexandrUrita** [comment]
Performance optimisation was done. @eistrati please confirm if you are ok with current behaviour (available only in dev branch)

**Comment by eistrati** [comment]
Looks much faster. I'm ok with this improved behavior and we can close this ticket. Side thought - let's see what our pilot customers are saying with this improvement?

**Comment by AlexandrUrita** [comment]
Moving ticket to Done
