### ISSUE TITLE
Save WP configuration into AdTechMedia platform

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/adtechmedia-wordpress-plugin#21]
We need some infrequent save of WP plugin configurations into AdTechMedia platform. Basically we want to learn from real world use cases and embed that learning into more useful features / better future releases.

**Comment by AlexanderC** [comment]
https://github.com/MitocGroup/atm/issues/595

**Comment by avozicov** [comment]
Tested on local environment with updated code from dev branch [2017-03-17] 
- Test Passed
