### ISSUE TITLE
Remove categories from Templates on WP

### ISSUE THREAD

**Issue by AlexandrUrita** [MitocGroup/adtechmedia-wordpress-plugin#216]
Steps to reproduce:
1. Navigate to WP with installed and activated plugin
2. Navigate to plugin
3. Scroll down the page till Templates section
4. Select Pledge -> Body Message
4a. Select Pay -> Body Message

Expected result: Should not be present -> 
- Advertising
- Micropayments
- Subscriptions

Actual result: Should remain only combinations: Advertising and Micropayments, Advertising and Subscriptions, Micropayments and Subscriptions

![screen shot 2017-08-23 at 12 06 08 pm](https://user-images.githubusercontent.com/27765884/29627243-2139be40-883a-11e7-86ba-605f86c8cdd6.png)

**Comment by AlexandrUrita** [comment]
@AlexanderC If changes that were made here will be applied on Manage site?

**Comment by AlexanderC** [comment]
Template widget reflects currently all possible combinations that could be costumized. Should we allow only the combinations for the selected country for the property? @AlexandrUrita

**Comment by AlexandrUrita** [comment]
Categories were removed:
![screen shot 2017-08-25 at 16 28 31](https://user-images.githubusercontent.com/27765884/29716035-754eb278-89b2-11e7-95ab-1accdacac02e.png)
