### ISSUE TITLE
Content is not blurred

### ISSUE THREAD

**Issue by ghost** [MitocGroup/adtechmedia-wordpress-plugin#22]
See attached: content is not blurred when `blur+scramble` or `blur` unlocking algorithm is selected.
Adtechmedia version: 0.4
Wordpress version: 4.7.1
Issue reproduces for all themes.

<img width="462" alt="screen shot 2017-01-16 at 10 30 26 am" src="https://cloud.githubusercontent.com/assets/10956412/21975723/f9c0cb8e-dbd6-11e6-9194-b3dd84ade649.png">
<img width="716" alt="screen shot 2017-01-16 at 10 30 18 am" src="https://cloud.githubusercontent.com/assets/10956412/21975724/f9c4944e-dbd6-11e6-9b3d-1ffc730bd089.png">

**Comment by eistrati** [comment]
Verified.
