### ISSUE TITLE
Save button is inactive after click

### ISSUE THREAD

**Issue by AlexandrUrita** [MitocGroup/adtechmedia-wordpress-plugin#227]
Steps to reproduce:
1. Navigate to WP
2. Activate Plugin and navigate to Adtechmedia plugin
3. Click on Save button

Expected result: After changes are saved button should be active

Actual result: After changes button is inactive
![screen shot 2017-09-01 at 13 52 50](https://user-images.githubusercontent.com/27765884/29967001-16d38c9e-8f1d-11e7-8550-b30978d6251b.png)

**Comment by AlexandrUrita** [comment]
Will be closed after this task will be resolved: https://github.com/AdTechMedia/wordpress-plugin/issues/231

**Comment by avozicov** [comment]
Test **Passed**
- Saving button is active after performing save actions
<img width="1280" alt="screen shot 2017-09-07 at 15 59 30" src="https://user-images.githubusercontent.com/12330493/30164578-a802a96c-93e5-11e7-91d5-58fd97bec1c2.png">
