### ISSUE TITLE
Plugin is not displayed

### ISSUE THREAD

**Issue by ghost** [MitocGroup/adtechmedia-wordpress-plugin#23]
Please refer to attachment: Adtechmedia plugin is not displayed at all.
Adtechmedia version: 0.4
Wordpress version: 4.7.1

<img width="1248" alt="screen shot 2017-01-16 at 10 53 22 am" src="https://cloud.githubusercontent.com/assets/10956412/21976351/0e1f046c-dbda-11e6-99ad-4078306c34ee.png">

**Comment by eistrati** [comment]
Verified.
