### ISSUE TITLE
WP plugin: User should not allowed to store 0 on Price

### ISSUE THREAD

**Issue by AlexandrUrita** [MitocGroup/adtechmedia-wordpress-plugin#230]
Steps to reproduce:
1. Navigate to WP Admin
2. Navigate to Adtechmedia plugin
3. Locate Content Pricing
4. Set this field to 0
5. Try to Save property

Expected result: Price should not be stored. Error message should be displayed

Actual result: Price is storing but after refresh field receives previous value
![screen shot 2017-09-04 at 15 24 26](https://user-images.githubusercontent.com/27765884/30026387-55f51bb2-9185-11e7-9034-b1dd9d5f501d.png)

**Comment by avozicov** [comment]
Test **Passed**
Validation has been implemented on calling Save action with 0 price field
<img width="1280" alt="screen shot 2017-09-07 at 16 30 36" src="https://user-images.githubusercontent.com/12330493/30165805-06ca4686-93ea-11e7-8e6a-7d4abf83c849.png">
