### ISSUE TITLE
Save button throws error message for the Templates

### ISSUE THREAD

**Issue by AlexandrUrita** [MitocGroup/adtechmedia-wordpress-plugin#231]
Steps to reproduce:
1. Navigate to WP with activated plugin
2. Navigate to Adtechmedia
3. Locate Templates Management section
4. Change and save some value under [Overall position and styling]
4a. Change and save some value under [Content editor]

Expected result: Templates should be stored w/o any error messages

Actual result: Error message is displayed

Note: that issue can be reproduced only ones for the first time:
![screen shot 2017-09-04 at 17 16 19](https://user-images.githubusercontent.com/27765884/30030686-1be74d0c-9197-11e7-9a69-a55857740679.png)

**Comment by avozicov** [comment]
Test **Passed**
- There are no errors when saving Templates changes, but there is an use case related to the following component which is described in new issue https://github.com/AdTechMedia/wordpress-plugin/issues/238
