### ISSUE TITLE
On Mobile: WP plugin corrupt gallery images

### ISSUE THREAD

**Issue by AlexandrUrita** [MitocGroup/adtechmedia-wordpress-plugin#249]
Steps to reproduce:
1. Navigate to activated WP plugin 
2. Navigate to mobile version of the post
3. Check for images that are present on the page

Expected result: Images should be available

Actual result: Images are not available

**Comment by ciolak** [comment]
Bug have not reproduced, gallery and plugin work well. Please provide more information

**Comment by AlexandrUrita** [comment]
Issue cannot be reproduced on our end. Lack of information

**Comment by eistrati** [comment]
Our customer reported that it was an issue on their end. Safe to close this issue now.
