### ISSUE TITLE
Add "I agree to Terms of Use" legal note next to Register button

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/adtechmedia-wordpress-plugin#25]
Please add the following legal note next to Register button:

`I agree to Terms of Use`

Update: When clicking on `I agree to Terms of Use`, display the content of https://www.adtechmedia.io/terms/dialog.html in a nice modal / dialog

**Comment by ghost** [comment]
See attached: left part of the modal is hidden behind the menu.

<img width="1278" alt="screen shot 2017-01-27 at 5 54 14 pm" src="https://cloud.githubusercontent.com/assets/10956412/22378026/aee2f95e-e4bc-11e6-9857-d4c081fa76d1.png">

**Comment by ghost** [comment]
Also please load content using AJAX instead of loading it in iframe

**Comment by eistrati** [comment]
Verified.
