### ISSUE TITLE
Use 'atmTpl.stories()' method to retrieve and use metadata for generating inputs content

### ISSUE THREAD

**Issue by ghost** [MitocGroup/adtechmedia-wordpress-plugin#27]
The names may be changed in future and they should be picked up automatically without any additional changes to the WP code.

See attached: atm content(1) doesn't coincide with WP content(2)

<img width="648" alt="screen_shot_2017-01-20_at_2_26_09_pm" src="https://cloud.githubusercontent.com/assets/10956412/22149482/b55b5254-df1c-11e6-8970-98db43f47690.png">

<img width="868" alt="screen_shot_2017-01-20_at_2_26_48_pm" src="https://cloud.githubusercontent.com/assets/10956412/22149483/b55c1900-df1c-11e6-8afd-996696178cdf.png">

**Comment by eistrati** [comment]
Verified.
