### ISSUE TITLE
Plugin is not responsive on different Wordpress themes

### ISSUE THREAD

**Issue by ghost** [MitocGroup/adtechmedia-wordpress-plugin#28]
Considering three default Wordpress themes **Twenty Fifteen**, **Twenty Sixteen**, **Twenty Seventeen**, plugin becomes not responsive on some point on any of them.

Please refer to attachments:

<img width="1110" alt="screen shot 2017-01-23 at 5 06 10 pm" src="https://cloud.githubusercontent.com/assets/10956412/22209192/441bfbc4-e18e-11e6-9d5c-a71aa597557a.png">

<img width="806" alt="screen shot 2017-01-23 at 12 24 33 pm" src="https://cloud.githubusercontent.com/assets/10956412/22209140/0d5ad966-e18e-11e6-8534-00c58ddbb597.png">

**Comment by AlexanderC** [comment]
Could be fixed by https://github.com/MitocGroup/atm/issues/856

**Comment by AlexanderC** [comment]
Try to apply a fast hotfix

**Comment by avozicov** [comment]
@AlexanderC  Changes become applied only after performing "Save" actions
Please implement required changes for responsive by default.

**Comment by avozicov** [comment]
Tested at Plugin version 0.8

**Comment by avozicov** [comment]
Bug is reproducing with the following config settings : 
- "Twenty Seventeen/Sixteen" theme is required to be activated
- "Sticky" option is required to be off 

Please refer to attachments for more details : 
<img width="1280" alt="screen shot 2017-03-22 at 19 11 24" src="https://cloud.githubusercontent.com/assets/12330493/24211486/eca3c71c-0f34-11e7-8e29-27e23e7a3aa9.png">

**Comment by AlexanderC** [comment]
Responsive should work on Mobile devices and other with the resolution lower than 922px
