### ISSUE TITLE
Empty 'Country' and 'Content Pricing' dropdowns in Configuration

### ISSUE THREAD

**Issue by ghost** [MitocGroup/adtechmedia-wordpress-plugin#33]
Please refer to attachment: there are no options in Country and Content Pricing dropdowns

<img width="481" alt="screen shot 2017-01-30 at 2 42 22 pm" src="https://cloud.githubusercontent.com/assets/10956412/22423658/5b94baa8-e6fb-11e6-8ce8-a78f26718aef.png">

<img width="903" alt="screen shot 2017-01-27 at 6 30 02 pm" src="https://cloud.githubusercontent.com/assets/10956412/22378582/ccfe2646-e4be-11e6-9dc3-b660d7d1a32f.png">

**Comment by eistrati** [comment]
Verified.
