### ISSUE TITLE
[Register] button becomes empty after clicking on it

### ISSUE THREAD

**Issue by ghost** [MitocGroup/adtechmedia-wordpress-plugin#34]
1) Open AdTechMedia plugin settings
2) Check 'I agree to Terms of Use' checkbox
3) Click on [Register] button (https://www.adtechmedia.io/admin/accounts/signup should be opened after this in the new tab) 
4) Switch back to AdTechMedia plugin settings tab

Please refer to attachment: [Register] button stays empty until any click on the page is performed.
Note: bug reproduces in Chrome and Firefox but not in Safari.

<img width="1276" alt="screen shot 2017-01-31 at 10 17 23 am" src="https://cloud.githubusercontent.com/assets/10956412/22459232/7154420c-e7a8-11e6-9d83-828667540fa2.png">

**Comment by eistrati** [comment]
Verified.
