### ISSUE TITLE
FF: [Register] button can be disabled despite ticked checkbox 

### ISSUE THREAD

**Issue by ghost** [MitocGroup/adtechmedia-wordpress-plugin#35]
Bug reproduces only in Firefox browser (version 51.0.1)

1. Open AdTechMedia plugin settings
2. Check 'I agree to Terms of Use' checkbox
3. Click on 'I agree to Terms of Use' link to open terms
4. Click on any link inside the terms ([https://www.adtechmedia.io/privacy/ ](url) at the very bottom)
5. Click on [Back] browser button

See attached - bug: 'I agree to Terms of Use' checkbox is still ticked but [Register] button is disabled. Please make sure that checkbox status always coincides with [Register] button status.

<img width="924" alt="screen shot 2017-01-31 at 11 39 03 am" src="https://cloud.githubusercontent.com/assets/10956412/22460691/b46a108e-e7ae-11e6-91ba-59a1a6f7f0ad.png">

**Comment by eistrati** [comment]
Verified.
