### ISSUE TITLE
Typo in error messages

### ISSUE THREAD

**Issue by ghost** [MitocGroup/adtechmedia-wordpress-plugin#36]
Please refer to attachment: change `by` in all error messages to `be`

<img width="1200" alt="screen shot 2017-01-31 at 2 12 16 pm" src="https://cloud.githubusercontent.com/assets/10956412/22464697/dbb90f5c-e7c0-11e6-8a43-69ce36d56acf.png">

<img width="414" alt="screen shot 2017-01-31 at 2 24 55 pm" src="https://cloud.githubusercontent.com/assets/10956412/22474090/9c88f5fe-e7e3-11e6-9f28-982d69b6181d.png">

**Comment by ghost** [comment]
Please change the end of the message back to `...must be a number.`

<img width="1177" alt="screen shot 2017-02-02 at 11 35 10 am" src="https://cloud.githubusercontent.com/assets/10956412/22544255/a7cba722-e93c-11e6-99c9-c653364138c6.png">

**Comment by eistrati** [comment]
Verified.
