### ISSUE TITLE
Input remains highlighted red after submitting valid data

### ISSUE THREAD

**Issue by ghost** [MitocGroup/adtechmedia-wordpress-plugin#37]
1) Open AdTechMedia plugin settings
2) Try to save CONTENT CONFIGURATION with invalid Content pricing/paywall/preview (e.g. negative value `-1`)
3) After error messages appears -> fix invalid data to valid one and Save again

Expected result: input should stop being highlighted red after saving.
Actual result - see attached: input is still highlighted red despite the fact that value is valid and Saving worked fine.

<img width="783" alt="screen_shot_2017-01-31_at_3_18_28_pm" src="https://cloud.githubusercontent.com/assets/10956412/22467157/290a88a2-e7cc-11e6-9f64-b9517c5532e6.png">

**Comment by eistrati** [comment]
Verified.
