### ISSUE TITLE
Two AJAX requests instead of one while updating templates

### ISSUE THREAD

**Issue by ghost** [MitocGroup/adtechmedia-wordpress-plugin#38]
1) Open AdTechMedia plugin settings
2) Update any input in TEMPLATES MANAGEMENT and click on [Save] button

See attached: two notification messages appear after saving and two AJAX requests are sent instead of one.

<img width="1280" alt="screen_shot_2017-01-31_at_4_50_59_pm" src="https://cloud.githubusercontent.com/assets/10956412/22469843/fee0b056-e7d5-11e6-849e-0691b62c14e0.png">

**Comment by eistrati** [comment]
Verified.
