### ISSUE TITLE
No error message after trying to save non-existing variable

### ISSUE THREAD

**Issue by ghost** [MitocGroup/adtechmedia-wordpress-plugin#42]
1) Open AdTechMedia admin page
2) Change any variable (add any letter, e.g. `user` -> `users`)
3) Click on [Save] button

Expected result: error message should be displayed saying that specified variable doesn't exist.
Actual result: nothing happens in UI and `Uncaught Error: Missing rendition component 'users' for option 'body-welcome' in template 'pledgeComponent'` appears in console. 

Please display error message: `Variable "variable-name" does not exist`

<img width="1278" alt="screen_shot_2017-02-02_at_2_34_33_pm" src="https://cloud.githubusercontent.com/assets/10956412/22550012/b4a60702-e956-11e6-8b72-2c69cb3be0c6.png">

**Comment by eistrati** [comment]
Verified.
