### ISSUE TITLE
Changes in Refund Template are not displayed in plugin

### ISSUE THREAD

**Issue by ghost** [MitocGroup/adtechmedia-wordpress-plugin#44]
1) Open AdTechMedia plugin configuration
2) Click on [Refund Template] in Templates Management
3) Change any content in the Refund template (bug was reproduced in `Message, Mood, Share` tabs) and click on [Save] button

Expected result: changes should be reflected in the plugin, on the post page.
Actual result: 'save_template' works fine and changes remain saved even after page refresh, but they're not displayed in plugin on the post page.
Note: bug reproduces only for the Refund template

**Comment by eistrati** [comment]
Verified.
