### ISSUE TITLE
Service workers should not be registered with http protocol

### ISSUE THREAD

**Issue by ghost** [MitocGroup/adtechmedia-wordpress-plugin#45]
Please refer to attachment: both plugin and the post content are not displayed. 

Service workers shouldn't be registered via http protocol but now they are.

<img width="1280" alt="screen shot 2017-02-08 at 3 47 36 pm" src="https://cloud.githubusercontent.com/assets/10956412/22739805/f6732f5c-ee15-11e6-9381-919b1d032082.png">

**Comment by eistrati** [comment]
Verified.
