### ISSUE TITLE
Tooltips overlap placeholders in Templates Management

### ISSUE THREAD

**Issue by ghost** [MitocGroup/adtechmedia-wordpress-plugin#46]
1) Open AdTechMedia plugin configuration
2) Scroll down to the `Templates Management` area

Please refer to the attachment: tooltips and placeholders overlap each other.

Bug reproduces in `Pledge`, `Pay`, `Refund` templates, in tabs `Salutation`, `Message`, `User`.

<img width="629" alt="screen shot 2017-02-08 at 4 05 19 pm" src="https://cloud.githubusercontent.com/assets/10956412/22740628/2c3db456-ee19-11e6-84dc-53d72e199ae0.png">

**Comment by avozicov** [comment]
Tested on local environment with updated code from dev branch [2017-03-17] 
- Test Passed
