### ISSUE TITLE
Plugin and post content are not displayed

### ISSUE THREAD

**Issue by ghost** [MitocGroup/adtechmedia-wordpress-plugin#47]
Issue reproduces after updating from dev branch, please refer to attachment:

<img width="1280" alt="screen shot 2017-02-08 at 3 47 36 pm" src="https://cloud.githubusercontent.com/assets/10956412/22740869/f17d22a6-ee19-11e6-8b04-862182505496.png">

**Comment by eistrati** [comment]
Verified.
