### ISSUE TITLE
Changes in 'Overall styling and position' are overridden after page refresh

### ISSUE THREAD

**Issue by ghost** [MitocGroup/adtechmedia-wordpress-plugin#48]
1) Open AdTechMedia plugin configuration
2) Change any value in `Overall styling and position` area and click on [Save] button
3) Refresh the page

Expected result: changed values should remain saved after refresh.
Actual result: changed values disappear after refresh and default ones are displayed.
Note: reproduces only in 'Overall styling and position' area.

**Comment by AlexanderC** [comment]
Unable to reproduce

**Comment by ghost** [comment]
The issues has been fixed and isn't reproducing anymore in the latest build.
