### ISSUE TITLE
Multiple error messages appear on every click

### ISSUE THREAD

**Issue by ghost** [MitocGroup/adtechmedia-wordpress-plugin#49]
1) Open AdTechMedia plugin configuration
2) Erase default value in `Email address`, check the `I agree to Terms of Use` and click on [Register] button
3) Click on [Register] again, couple of times

Please refer to attachment: separate error message appears on every click
Note: reproduces in `Content configuration` as well, in `Content pricing/content paywall/content preview` fields

![ezgif com-video-to-gif 3](https://cloud.githubusercontent.com/assets/10956412/22745472/52a6c83e-ee29-11e6-81b9-c8a65f4c3380.gif)

**Comment by avozicov** [comment]
Tested on local environment with updated code from dev branch [2017-03-16] 
- Test Passed

**Comment by avozicov** [comment]
Bug is reproducing in new dev build and for all fields on widget configuration.
I have listed the required fields and created new task to exclude misunderstanding https://github.com/AdTechMedia/wordpress-plugin/issues/62
