### ISSUE TITLE
Plugin is not working after changing endpoint to dev

### ISSUE THREAD

**Issue by ghost** [MitocGroup/adtechmedia-wordpress-plugin#51]
1) Install AdTechMedia plugin, activate it
2) Open `wp-content/plugins/adtechmedia/adtechmedia-config.php` file and change `api` to `api-dev` in 'api_end_point' and 'sw_js_url', save the changes
3) Open any post

Please refer to attachment: plugin and post content are not displayed, `api` endpoint is still established.

<img width="1280" alt="screen_shot_2017-02-09_at_2_17_26_pm" src="https://cloud.githubusercontent.com/assets/10956412/22783038/a91370ec-eed2-11e6-800d-be18528f86f1.png">

**Comment by AlexanderC** [comment]
Not more relevant, configs were changes
