### ISSUE TITLE
User's settings are still applied after returning to default values

### ISSUE THREAD

**Issue by ghost** [MitocGroup/adtechmedia-wordpress-plugin#52]
1) Open AdTechMedia plugin configuration
2) Change any value in any template (e.g. `Dear {user} ,` into `Hello {user} ,` in 'Salutation' tab)
3) Click on [Save] button and wait for the notification message to appear: 'AdTechMedia parameters have been saved successfully'
4) Click on [RESET TO DEFAULT VALUES] button and wait for the notification message to appear: 'AdTechMedia parameters have been return to default values'
5) Open any post

Expected result: default values must be displayed in the plugin
Actual result: old user's values are still displayed.

Bug reproduces in "Templates management" but only in the templates themselves. Returning to default parameters in 'Overall styling and position' area works fine.

**Comment by avozicov** [comment]
Tested on local environment with updated code from dev branch [2017-03-17] 
- Test **Failed**

Bug is reproducing with the same behavior as described in the issue details

**Comment by AlexanderC** [comment]
Please provide more details, like browser version, WP version, server, php version etc.
