### ISSUE TITLE
Wrong notification message throttling for widget configuration 

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/adtechmedia-wordpress-plugin#62]
_Pre-requisites:_ 
- ATM Plugin should be installed and activated  
- ATM Plugin Configuration page should be accessible 

_Steps to Reproduce:_

1. Navigate to [Plugins/Adtechmedia/Templates Management] page
2. Remove required value from "Salutation" field 
3. Focus on notification message behavior  

BUG:
Wrong throttling is set for notification message
(validation is applied for each introduced character)

_Please refer to attachment for more details:_

_Please refer to the check-list of fields where throttling is required to be fixed:_

PLEDGE TEMPLATE
- [x] Salutation / Salutation 
- [x] Message / Message (Expanded View)
- [x] Message / Message (Collapsed View)
- [x] User / Connect Message 
- [x] User / Disconnect Message
- [ ] Button / Micropayments Button Text

PAY TEMPLATE
- [x] Salutation / Salutation 
- [x] Message / Message (Expanded View)
- [x] Message / Message (Collapsed View)
- [x] User / Connect Message 
- [x] User / Disconnect Message

REFUND TEMPLATE
- [x] Message / Message (Expanded View)
- [x] Message / Message (Collapsed View)

OTHER TEMPLATES 
- [ ] Price / Price

**Comment by avozicov** [comment]
Notification message is not triggered for the unchecked items from task description.
Please refer to attachment for more details.
<img width="1280" alt="screen shot 2017-03-22 at 18 59 44" src="https://cloud.githubusercontent.com/assets/12330493/24210433/c593c26a-0f31-11e7-9261-8a007d441578.png">

**Comment by AlexanderC** [comment]
Price is not yet implemented
