### ISSUE TITLE
Enable advertising by default

### ISSUE THREAD

**Issue by AlexanderC** [MitocGroup/adtechmedia-wordpress-plugin#63]

**Comment by AlexanderC** [comment]
Test case: Reinstall plugin and check the default revenue method to be `advertising+micropayments`

**Comment by avozicov** [comment]
Test was performed on local server with updated code from "fixes" branch.
Test Failed 
reported in the separate issue : 
https://github.com/AdTechMedia/wordpress-plugin/issues/64

_Issue Details :_ 
- video is not displayed after user click on "Show Ad" button 

OS version : macOs Sierra 10.12.3 
Browser version : Chrome Version 57.0.2987.98

**Comment by avozicov** [comment]
Tested on local environment with updated code from "fixes branch" [2017-03-21] 
- Test Passed
