### ISSUE TITLE
Implement async plugin activation

### ISSUE THREAD

**Issue by AlexanderC** [MitocGroup/adtechmedia-wordpress-plugin#69]
Implement async plugin activation by adding async calls to cron to run immediately after it

**Comment by AlexandrUrita** [comment]
New dev build received for QA on 07.07.2017

**Comment by AlexandrUrita** [comment]
async plugin is added. After user clicks on link, loading icon is displayed to show that some processes are running:
![screen shot 2017-07-07 at 11 02 46](https://user-images.githubusercontent.com/27765884/27948898-29e0fac8-6304-11e7-8fbf-0965ef0f3e22.png)

**Comment by AlexandrUrita** [comment]
Improvement was made for the second activation on existing account.
First activation runs too long

**Comment by ciolak** [comment]
Во время нажатия активация выполняются 4 функции:

$this->check_api_key_exists();
$this->check_prop();
$this->update_prop();
$this->update_appearance();

Время активации примерно 30-40 секунд.

Проанализировав, я понял что можно удалить $this->check_prop();  ,потому что, эта функция вызывается при заходе на страницу плагина.

Так же можно выключить $this->update_prop(); , т.к. она вызывается в конце $this->check_prop();

Остаются:
$this->check_api_key_exists();
$this->update_appearance();

Время активации примерно 20-30 секунд.

$this->update_appearance(); из них занимает где то 70% времени

Но все это надо тестить.

**Comment by AlexandrUrita** [comment]
Activation of plugin takes 6 seconds for the first time. And for the same email for second time less than 5 seconds
