### ISSUE TITLE
Integrate deep-account changes

### ISSUE THREAD

**Issue by AlexanderC** [MitocGroup/adtechmedia-wordpress-plugin#70]

**Comment by avozicov** [comment]
Confirmation testing is blocked by the following task 
https://github.com/AdTechMedia/wordpress-plugin/issues/79

**Comment by avozicov** [comment]
<img width="1280" alt="screen shot 2017-05-04 at 17 23 42" src="https://cloud.githubusercontent.com/assets/12330493/25708233/92385c4e-30ee-11e7-80fa-9f0fa023c4d1.png">
