### ISSUE TITLE
Templates settings are not applied to "ATM Plugin" template

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/adtechmedia-wordpress-plugin#72]
_Pre-requisites:_ 
- ATM Plugin should be installed and activated on content page

_Steps to reproduce:_
- Navigate to "General Configuration" page
- Add "test" message to "Pledge" template in the "Message" field and save/apply changes 

BUG:
Changes made in general configuration are not applied on ATM Plugin 

_Issue details:_
- Bug is also reproducing for "Payment" view with the same behavior 
- Bug has started to reproduce after switching Advertising + micropayments revenue method and is reproducing only for "Advertising/  Advertising + micropayments" revenue methods

_Please refer to attachment for more details:_ 

<img width="992" alt="screen shot 2017-03-23 at 18 21 06" src="https://cloud.githubusercontent.com/assets/12330493/24258278/ea6042e8-0ff5-11e7-861c-6b7b6c3b0e42.png">

**Comment by ivignan** [comment]
Requires Template payments refactoring

**Comment by AlexandrUrita** [comment]
Issue is not reproduced. Please refer on the screenshots below:
![screen shot 2017-06-19 at 17 37 15](https://user-images.githubusercontent.com/27765884/27290693-adf454be-5516-11e7-87b9-a1542d8bdca6.png)
![screen shot 2017-06-19 at 17 35 49](https://user-images.githubusercontent.com/27765884/27290694-adf46ca6-5516-11e7-8355-2e5409ff92e2.png)
![screen shot 2017-06-19 at 17 36 13](https://user-images.githubusercontent.com/27765884/27290692-adf1d414-5516-11e7-951b-18c1ed0220ee.png)
