### ISSUE TITLE
Plugin got "stocked" and "unlock content" actions can not be performed

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/adtechmedia-wordpress-plugin#75]
- Bug is reproducing on Prod Env
 
_Steps to reproduce:_
1.  Navigate to the following url http://dev-adtechmedia-wordpress.pantheonsite.io/2017/03/20/why-just-blocking-the-adblockers-doesnt-work/
2. Click on "Unlock Premium Content" button 

_BUG:_ 
- Plugin got "stocked" and "unlock content" actions can not be performed

_Issue details:_
- Plugin window is not visible 
- Content is blurred and scrumbled but "unlock content" actions can not be performed
- Nothing happens when clicking on "Unlock Premium Content" button 
- There is an error in console displayed with the response "Uncaught (in promise) DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV). wpswmanager_sw-registrar.js?ver=4.7.3:14"

_Note:_ 
- Bug is reproducing randomly and for random content pages

_Please refer to attachment for more details:_
<img width="1280" alt="screen shot 2017-04-04 at 15 02 28" src="https://cloud.githubusercontent.com/assets/12330493/24655649/bd393558-1947-11e7-9ce7-48318b4d4234.png">

**Comment by AlexanderC** [comment]
Waiting for merging changes done for deep-aacount integration, this may be fixed, but couldn't be tested until Api deployed
