### ISSUE TITLE
Error encoding config with json_encode

### ISSUE THREAD

**Issue by AlexanderC** [MitocGroup/adtechmedia-wordpress-plugin#80]
PHPs json_encode encoding issues that breaks functionality by leaving special characters unencoded

**Comment by avozicov** [comment]
<img width="1280" alt="screen shot 2017-05-03 at 15 23 38" src="https://cloud.githubusercontent.com/assets/12330493/25660368/943f78a4-3014-11e7-930f-7d0aa31fb959.png">

<img width="1280" alt="screen shot 2017-05-03 at 15 23 48" src="https://cloud.githubusercontent.com/assets/12330493/25660362/8bc86410-3014-11e7-9fa5-930229958bc3.png">
