### ISSUE TITLE
Get rid of hardcoded links to ATM platform and APIs

### ISSUE THREAD

**Issue by AlexanderC** [MitocGroup/adtechmedia-wordpress-plugin#89]
Get rid of **ALL** hardcoded links to ATM platform and APIs

**Comment by avozicov** [comment]
**Test Passed** 
Please refer to the following pull request for details:
https://github.com/AdTechMedia/wordpress-plugin/commit/2ac0e8bd51b9cc976f2516d27e4535abb3f07fec
