### ISSUE TITLE
Add refund confirmation into Templates Management

### ISSUE THREAD

**Issue by AlexanderC** [MitocGroup/adtechmedia-wordpress-plugin#91]
Please add 'Refund confirmation' field into Message tab, in Refund template.
Add this text as default: `Original charge has been refunded. Thanks for continue supporting quality journalism.`

![Screenshot](https://cloud.githubusercontent.com/assets/10956412/22514499/2cfa32c8-e8a8-11e6-8719-7564fd0ef5d6.png)

**Comment by AlexandrUrita** [comment]
Refund section was added. Please refer to the screenshot below:

![screen shot 2017-06-19 at 17 47 50](https://user-images.githubusercontent.com/27765884/27290982-8720107a-5517-11e7-84fd-fd3c812be5fa.png)
