### ISSUE TITLE
Add refund modal into template management

### ISSUE THREAD

**Issue by AlexanderC** [MitocGroup/adtechmedia-wordpress-plugin#92]
Please refer to the attachment: there is no Refund Confirmation message

![Screenshot](https://cloud.githubusercontent.com/assets/10956412/23698471/5873d802-03f4-11e7-9f48-39020e389862.png)

**Comment by AlexandrUrita** [comment]
Refund template was added. Please refer to the screenshot below:
![screen shot 2017-06-19 at 17 24 48](https://user-images.githubusercontent.com/27765884/27289966-6bebedfe-5514-11e7-807b-367d38f5557e.png)
