### ISSUE TITLE
Make "Unlock Content" template management functional

### ISSUE THREAD

**Issue by AlexanderC** [MitocGroup/adtechmedia-wordpress-plugin#94]

**Comment by AlexandrUrita** [comment]
Unlock Content section is not present on Templates Management. Return enhancement in TO DO. Please refer on screenshot below:
![screen shot 2017-06-19 at 17 56 40](https://user-images.githubusercontent.com/27765884/27291366-b1464eae-5518-11e7-80e9-16a123ec8da8.png)

**Comment by AlexandrUrita** [comment]
Issue is fixed. Please see screenshot below:
![screen shot 2017-06-29 at 18 25 50](https://user-images.githubusercontent.com/27765884/27695744-75f0241e-5cf8-11e7-9960-5760710e8f0d.png)
