### ISSUE TITLE
Caching issues in plugin

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/adtechmedia-wordpress-plugin#98]
Here are the steps to reproduce it:
1. Remove currently installed AdTechMedia plugin
2. Load an article in a different browser
3. Install and activate AdTechMedia plugin from WordPress.org
4. Refresh the article from different browser

Result: Plugin doesn't scramble content and everything is opened (feels like plugin execution doesn't trigger)
Expectation: Content should be scrambled

**Comment by AlexandrUrita** [comment]
Issue is not reproduced. 
Were used steps that are described in current task.
If plugin is not registered scrambled mode will not be applied. Were used Chrome and Safari. (activation from Chrome)

Note: After deactivating and activating back plugin all changes that were made before deactivation are saved and applied on text successfully.
