### ISSUE TITLE
"Email" address field does not send its value during "Register" request 

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/adtechmedia-wordpress-plugin#99]
_Pre-requisites:_
- ATM Plugin should be already installed and activated on WordPress

_Steps to reproduce:_
- Acces to "AdTechMedia Plugin" configuration page 
- Change actual "email address - X" to a new one "Y" on "email address" field 
- Click on "Register button"

_Actual Result:_
- User is redirected to "Admin" page but " X email address" is stored on "New Customer" modal in spite the fact that "Y email address" was added before submitting the request  
- By performing "register" action - default wordpress email is used and form filed value is not applied on request 

_Enhancement:_
- Remove "email address field" from "AdTechMedia Plugin" configuration page 
- Notify user that "WordPress default email address" will be used for "AdTechMedia Plugin" registration (this can be applied by changing the text bellow the field) (attachment 1)

_Please refer to attachment for more details:_
- Default email address used for WP installation 
<img width="437" alt="screen shot 2017-06-13 at 10 56 37" src="https://user-images.githubusercontent.com/12330493/27071807-01c6aa82-5027-11e7-928b-b82adc8ee332.png">

- New introduced email address for performing plugin registration action 
<img width="419" alt="screen shot 2017-06-13 at 10 46 40" src="https://user-images.githubusercontent.com/12330493/27071833-177faca2-5027-11e7-9c0c-26537ed84edf.png">

- Email address which is displayed on request submit after redirect to "admin" page
<img width="1263" alt="screen shot 2017-06-13 at 10 47 06" src="https://user-images.githubusercontent.com/12330493/27071852-2b0548fe-5027-11e7-8f14-9b74576c32d3.png">

**Comment by AlexandrUrita** [comment]
Build was received for QA on 14.07.2017 (new environment was created www-test)

**Comment by AlexandrUrita** [comment]
Was modified behaviour of the register field. Now it is not editable. All processes are working as expected. Please see screenshots below:
![screen shot 2017-07-17 at 13 04 36](https://user-images.githubusercontent.com/27765884/28265282-8e3227c2-6af7-11e7-9e32-870f581b0f68.png)
![screen shot 2017-07-17 at 13 53 59](https://user-images.githubusercontent.com/27765884/28265281-8e2f86d4-6af7-11e7-83f7-655ce0829276.png)
